In [1]:
#Importando Dependenciais iniciais
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
# Acessando dados
df = pd.read_csv("/home/luis/Projetos/scooutMax/data/cooper/BRA.csv")

# ANÁLISE EXPLORATÓRIA DOS DADOS

In [3]:
# Os 5 primeros
df.head()

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,...,MaxCA,AvgCH,AvgCD,AvgCA,BFECH,BFECD,BFECA,B365CH,B365CD,B365CA
0,Brazil,Serie A,2012,19/05/2012,22:30,Palmeiras,Portuguesa,1.0,1.0,D,...,5.31,1.69,3.50,4.90,NaN,NaN,NaN,NaN,NaN,NaN
1,Brazil,Serie A,2012,19/05/2012,22:30,Sport Recife,Flamengo RJ,1.0,1.0,D,...,2.70,2.59,3.23,2.58,NaN,NaN,NaN,NaN,NaN,NaN
2,Brazil,Serie A,2012,20/05/2012,01:00,Figueirense,Nautico,2.0,1.0,H,...,7.22,1.59,3.67,5.64,NaN,NaN,NaN,NaN,NaN,NaN
3,Brazil,Serie A,2012,20/05/2012,20:00,Botafogo RJ,Sao Paulo,4.0,2.0,H,...,3.15,2.35,3.26,2.84,NaN,NaN,NaN,NaN,NaN,NaN
4,Brazil,Serie A,2012,20/05/2012,20:00,Corinthians,Fluminense,0.0,1.0,A,...,4.41,1.89,3.33,3.89,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# As ultimas linhas
df.tail()

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,...,MaxCA,AvgCH,AvgCD,AvgCA,BFECH,BFECD,BFECA,B365CH,B365CD,B365CA
5560,Brazil,Serie A,2026,30/08/2026,20:00,Flamengo RJ,Botafogo RJ,3.0,0.0,H,...,11.00,1.28,5.55,9.37,1.32,6.20,11.5,1.25,5.75,10.00
5561,Brazil,Serie A,2026,30/08/2026,22:30,Gremio,Chapecoense-SC,3.0,1.0,H,...,6.50,1.52,4.01,6.05,1.57,4.30,7.4,1.49,4.00,6.50
5562,Brazil,Serie A,2026,30/08/2026,22:30,Mirassol,Palmeiras,1.0,1.0,D,...,2.15,3.42,3.30,2.10,3.80,3.45,2.2,3.70,3.50,2.01
5563,Brazil,Serie A,2026,30/08/2026,23:30,Bahia,Internacional,3.0,2.0,H,...,4.50,1.78,3.58,4.28,1.88,3.75,4.8,1.76,3.60,4.50
5564,Brazil,Serie A,2026,01/09/2026,00:00,Remo,Coritiba,2.0,3.0,A,...,3.80,2.04,3.20,3.70,2.16,3.35,4.0,2.05,3.30,3.75

In [5]:
# quantidade de Colunas
df.shape[1]

25

In [6]:
# quantidade de linhas
df.shape[0]

5565

In [7]:
# Nomes das colunas
df.columns

Index(['Country', 'League', 'Season', 'Date', 'Time', 'Home', 'Away', 'HG',
       'AG', 'Res', 'PSCH', 'PSCD', 'PSCA', 'MaxCH', 'MaxCD', 'MaxCA', 'AvgCH',
       'AvgCD', 'AvgCA', 'BFECH', 'BFECD', 'BFECA', 'B365CH', 'B365CD',
       'B365CA'],
      dtype='str')

In [48]:
# verificando a integridade das tipagem
df.dtypes

Country        str
League         str
Season       int64
Date           str
Time           str
Home           str
Away           str
HG         float64
AG         float64
Res            str
PSCH       float64
PSCD       float64
PSCA       float64
MaxCH      float64
MaxCD      float64
MaxCA      float64
AvgCH      float64
AvgCD      float64
AvgCA      float64
BFECH      float64
BFECD      float64
BFECA      float64
B365CH     float64
B365CD     float64
B365CA     float64
dtype: object

In [8]:
# Mostra informações do .csv
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5565 entries, 0 to 5564
Data columns (total 25 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  5565 non-null   str
 1   League   5565 non-null   str
 2   Season   5565 non-null   int64
 3   Date     5565 non-null   str
 4   Time     5565 non-null   str
 5   Home     5565 non-null   str
 6   Away     5565 non-null   str
 7   HG       5564 non-null   float64
 8   AG       5564 non-null   float64
 9   Res      5564 non-null   str
 10  PSCH     5275 non-null   float64
 11  PSCD     5275 non-null   float64
 12  PSCA     5275 non-null   float64
 13  MaxCH    5565 non-null   float64
 14  MaxCD    5565 non-null   float64
 15  MaxCA    5565 non-null   float64
 16  AvgCH    5565 non-null   float64
 17  AvgCD    5565 non-null   float64
 18  AvgCA    5565 non-null   float64
 19  BFECH    830 non-null    float64
 20  BFECD    830 non-null    float64
 21  BFECA    830 non-null    float64
 22  B365CH   447 non-null    float64
 23  B365CD   447 non-null    float64
 24  B365CA   447 non-null    float64
dtypes: float64(17), int64(1), str(7)
memory usage: 1.1 MB

In [9]:
# descreve estáticas de cala coluna como(contagem, média, mínimo, max, etc...)
df.describe(include="all")

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,...,MaxCA,AvgCH,AvgCD,AvgCA,BFECH,BFECD,BFECA,B365CH,B365CD,B365CA
count,5565,5565,5565.000000,5565,5565,5565,5565,5564.000000,5564.000000,5564,...,5565.000000,5565.000000,5565.000000,5565.000000,830.000000,830.000000,830.000000,447.000000,447.000000,447.000000
unique,1,1,NaN,1620,40,38,38,NaN,NaN,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Brazil,Serie A,NaN,06/12/2015,20:00,Corinthians,Flamengo RJ,NaN,NaN,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,5565,5565,NaN,10,1100,279,279,NaN,NaN,2695,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,2018.830189,NaN,NaN,NaN,NaN,1.424874,0.973221,NaN,...,4.893098,2.236171,3.487184,4.325668,2.410024,3.689229,4.922434,2.265123,3.567383,4.372192
std,NaN,NaN,4.231454,NaN,NaN,NaN,NaN,1.160622,0.985150,NaN,...,2.708016,0.885346,0.576184,2.127862,1.092684,0.735105,2.881373,0.971048,0.665208,2.256791
min,NaN,NaN,2012.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,...,0.000000,1.070000,2.510000,1.150000,1.160000,2.820000,1.380000,1.130000,2.750000,1.350000
25%,NaN,NaN,2015.000000,NaN,NaN,NaN,NaN,1.000000,0.000000,NaN,...,3.050000,1.670000,3.140000,2.860000,1.760000,3.250000,3.100000,1.660000,3.200000,2.850000
50%,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,...,4.150000,2.030000,3.300000,3.760000,2.120000,3.450000,4.200000,1.960000,3.400000,3.900000
75%,NaN,NaN,2022.000000,NaN,NaN,NaN,NaN,2.000000,2.000000,NaN,...,6.000000,2.530000,3.660000,5.260000,2.700000,3.850000,5.875000,2.560000,3.750000,5.250000
max,NaN,NaN,2026.000000,NaN,NaN,NaN,NaN,8.000000,6.000000,NaN,...,36.000000,20.230000,10.820000,26.580000,11.500000,9.600000,24.000000,9.000000,7.500000,17.000000

In [10]:
# Selecionando uma coluna --> 
df["Country"]

0       Brazil
1       Brazil
2       Brazil
3       Brazil
4       Brazil
         ...
5560    Brazil
5561    Brazil
5562    Brazil
5563    Brazil
5564    Brazil
Name: Country, Length: 5565, dtype: str

In [11]:
# Selecionanado mais de uma coluna
df[["Country","League","Home","Away"]]

     Country   League          Home            Away
0     Brazil  Serie A     Palmeiras      Portuguesa
1     Brazil  Serie A  Sport Recife     Flamengo RJ
2     Brazil  Serie A   Figueirense         Nautico
3     Brazil  Serie A   Botafogo RJ       Sao Paulo
4     Brazil  Serie A   Corinthians      Fluminense
...      ...      ...           ...             ...
5560  Brazil  Serie A   Flamengo RJ     Botafogo RJ
5561  Brazil  Serie A        Gremio  Chapecoense-SC
5562  Brazil  Serie A      Mirassol       Palmeiras
5563  Brazil  Serie A         Bahia   Internacional
5564  Brazil  Serie A          Remo        Coritiba

[5565 rows x 4 columns]

In [12]:
# Selecionando pela primeiro dados
df.iloc[0]

Country        Brazil
League        Serie A
Season           2012
Date       19/05/2012
Time            22:30
Home        Palmeiras
Away       Portuguesa
HG                1.0
AG                1.0
Res                 D
PSCH             1.75
PSCD             3.86
PSCA             5.25
MaxCH            1.76
MaxCD            3.87
MaxCA            5.31
AvgCH            1.69
AvgCD             3.5
AvgCA             4.9
BFECH             NaN
BFECD             NaN
BFECA             NaN
B365CH            NaN
B365CD            NaN
B365CA            NaN
Name: 0, dtype: object

In [13]:
# selecionando 1 linha
df.iloc[0:5]

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,...,MaxCA,AvgCH,AvgCD,AvgCA,BFECH,BFECD,BFECA,B365CH,B365CD,B365CA
0,Brazil,Serie A,2012,19/05/2012,22:30,Palmeiras,Portuguesa,1.0,1.0,D,...,5.31,1.69,3.50,4.90,NaN,NaN,NaN,NaN,NaN,NaN
1,Brazil,Serie A,2012,19/05/2012,22:30,Sport Recife,Flamengo RJ,1.0,1.0,D,...,2.70,2.59,3.23,2.58,NaN,NaN,NaN,NaN,NaN,NaN
2,Brazil,Serie A,2012,20/05/2012,01:00,Figueirense,Nautico,2.0,1.0,H,...,7.22,1.59,3.67,5.64,NaN,NaN,NaN,NaN,NaN,NaN
3,Brazil,Serie A,2012,20/05/2012,20:00,Botafogo RJ,Sao Paulo,4.0,2.0,H,...,3.15,2.35,3.26,2.84,NaN,NaN,NaN,NaN,NaN,NaN
4,Brazil,Serie A,2012,20/05/2012,20:00,Corinthians,Fluminense,0.0,1.0,A,...,4.41,1.89,3.33,3.89,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# selecionando de 0 a 5 linhas e de 0 a 3 colunas
df.iloc[0:5, 0:3]

  Country   League  Season
0  Brazil  Serie A    2012
1  Brazil  Serie A    2012
2  Brazil  Serie A    2012
3  Brazil  Serie A    2012
4  Brazil  Serie A    2012

In [15]:
# Selecionando por condição
df.loc[df["Home"] == "Flamengo RJ"]

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,...,MaxCA,AvgCH,AvgCD,AvgCA,BFECH,BFECD,BFECA,B365CH,B365CD,B365CA
11,Brazil,Serie A,2012,26/05/2012,22:30,Flamengo RJ,Internacional,3.0,3.0,D,...,4.20,1.99,3.23,3.74,NaN,NaN,NaN,NaN,NaN,NaN
30,Brazil,Serie A,2012,09/06/2012,22:30,Flamengo RJ,Coritiba,3.0,1.0,H,...,4.75,1.93,3.34,3.83,NaN,NaN,NaN,NaN,NaN,NaN
44,Brazil,Serie A,2012,17/06/2012,20:00,Flamengo RJ,Santos,1.0,0.0,H,...,5.65,1.63,3.65,5.12,NaN,NaN,NaN,NaN,NaN,NaN
66,Brazil,Serie A,2012,01/07/2012,22:30,Flamengo RJ,Atletico GO,3.0,2.0,H,...,6.00,1.59,3.71,5.44,NaN,NaN,NaN,NaN,NaN,NaN
95,Brazil,Serie A,2012,19/07/2012,01:50,Flamengo RJ,Corinthians,0.0,3.0,A,...,3.10,2.38,3.20,2.89,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5481,Brazil,Serie A,2026,24/05/2026,01:00,Flamengo RJ,Palmeiras,0.0,3.0,A,...,5.50,1.73,3.43,4.77,1.84,3.6,5.4,1.71,3.40,5.0
5488,Brazil,Serie A,2026,30/05/2026,20:00,Flamengo RJ,Coritiba,3.0,0.0,H,...,9.50,1.32,5.08,8.16,1.37,5.6,10.0,1.30,5.50,8.0
5515,Brazil,Serie A,2026,26/07/2026,22:30,Flamengo RJ,Sao Paulo,1.0,1.0,D,...,8.20,1.41,4.32,7.26,1.48,4.7,8.4,1.39,4.50,7.5
5534,Brazil,Serie A,2026,09/08/2026,23:30,Flamengo RJ,Vitoria,2.0,0.0,H,...,13.00,1.23,5.76,11.23,1.28,6.2,15.5,1.22,5.75,13.0
5560,Brazil,Serie A,2026,30/08/2026,20:00,Flamengo RJ,Botafogo RJ,3.0,0.0,H,...,11.00,1.28,5.55,9.37,1.32,6.2,11.5,1.25,5.75,10.0

In [16]:
# filtragem com &
df[
        (df["Country"] == "Brazil")
        &
        (df["AG"] > 3.0)
        ]

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,...,MaxCA,AvgCH,AvgCD,AvgCA,BFECH,BFECD,BFECA,B365CH,B365CD,B365CA
56,Brazil,Serie A,2012,24/06/2012,22:30,Atletico GO,Fluminense,1.0,4.0,A,...,2.76,2.80,3.22,2.41,NaN,NaN,NaN,NaN,NaN,NaN
81,Brazil,Serie A,2012,14/07/2012,22:30,Figueirense,Atletico-MG,3.0,4.0,A,...,3.00,2.47,3.24,2.70,NaN,NaN,NaN,NaN,NaN,NaN
100,Brazil,Serie A,2012,21/07/2012,22:30,Sport Recife,Atletico-MG,1.0,4.0,A,...,2.25,3.30,3.30,2.09,NaN,NaN,NaN,NaN,NaN,NaN
112,Brazil,Serie A,2012,26/07/2012,00:30,Nautico,Coritiba,3.0,4.0,A,...,3.40,2.14,3.32,3.19,NaN,NaN,NaN,NaN,NaN,NaN
228,Brazil,Serie A,2012,09/09/2012,22:30,Vasco,Bahia,0.0,4.0,A,...,6.70,1.57,3.74,5.68,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5427,Brazil,Serie A,2026,18/04/2026,22:30,Chapecoense-SC,Botafogo RJ,1.0,4.0,A,...,2.10,3.49,3.41,2.02,NaN,NaN,NaN,3.70,3.60,1.96
5445,Brazil,Serie A,2026,27/04/2026,00:30,Atletico-MG,Flamengo RJ,0.0,4.0,A,...,1.80,4.60,3.47,1.74,NaN,NaN,NaN,4.75,3.60,1.71
5504,Brazil,Serie A,2026,23/07/2026,01:30,Chapecoense-SC,Flamengo RJ,0.0,4.0,A,...,1.40,8.15,4.60,1.35,10.5,5.10,1.4,8.50,4.75,1.35
5522,Brazil,Serie A,2026,30/07/2026,01:30,Vitoria,Palmeiras,0.0,4.0,A,...,2.02,3.99,3.09,1.96,4.5,3.25,2.1,4.20,3.00,1.96
5541,Brazil,Serie A,2026,16/08/2026,22:30,Mirassol,Flamengo RJ,1.0,5.0,A,...,1.85,4.25,3.49,1.81,4.9,3.65,1.9,4.50,3.50,1.79

In [17]:
# filtragem com |(ou)
df[
        (df["Country"] == "Brazil")
        |
        (df["AG"] > 3.0)
        ]

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,...,MaxCA,AvgCH,AvgCD,AvgCA,BFECH,BFECD,BFECA,B365CH,B365CD,B365CA
0,Brazil,Serie A,2012,19/05/2012,22:30,Palmeiras,Portuguesa,1.0,1.0,D,...,5.31,1.69,3.50,4.90,NaN,NaN,NaN,NaN,NaN,NaN
1,Brazil,Serie A,2012,19/05/2012,22:30,Sport Recife,Flamengo RJ,1.0,1.0,D,...,2.70,2.59,3.23,2.58,NaN,NaN,NaN,NaN,NaN,NaN
2,Brazil,Serie A,2012,20/05/2012,01:00,Figueirense,Nautico,2.0,1.0,H,...,7.22,1.59,3.67,5.64,NaN,NaN,NaN,NaN,NaN,NaN
3,Brazil,Serie A,2012,20/05/2012,20:00,Botafogo RJ,Sao Paulo,4.0,2.0,H,...,3.15,2.35,3.26,2.84,NaN,NaN,NaN,NaN,NaN,NaN
4,Brazil,Serie A,2012,20/05/2012,20:00,Corinthians,Fluminense,0.0,1.0,A,...,4.41,1.89,3.33,3.89,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5560,Brazil,Serie A,2026,30/08/2026,20:00,Flamengo RJ,Botafogo RJ,3.0,0.0,H,...,11.00,1.28,5.55,9.37,1.32,6.20,11.5,1.25,5.75,10.00
5561,Brazil,Serie A,2026,30/08/2026,22:30,Gremio,Chapecoense-SC,3.0,1.0,H,...,6.50,1.52,4.01,6.05,1.57,4.30,7.4,1.49,4.00,6.50
5562,Brazil,Serie A,2026,30/08/2026,22:30,Mirassol,Palmeiras,1.0,1.0,D,...,2.15,3.42,3.30,2.10,3.80,3.45,2.2,3.70,3.50,2.01
5563,Brazil,Serie A,2026,30/08/2026,23:30,Bahia,Internacional,3.0,2.0,H,...,4.50,1.78,3.58,4.28,1.88,3.75,4.8,1.76,3.60,4.50
5564,Brazil,Serie A,2026,01/09/2026,00:00,Remo,Coritiba,2.0,3.0,A,...,3.80,2.04,3.20,3.70,2.16,3.35,4.0,2.05,3.30,3.75

In [24]:
df[df["HG"].isin([7.0,8.0])]  #checanfo resultando onde a casa marca de 7 a 8 gols

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,...,MaxCA,AvgCH,AvgCD,AvgCA,BFECH,BFECD,BFECA,B365CH,B365CD,B365CA
4456,Brazil,Serie A,2023,22/10/2023,20:00,Internacional,Santos,7.0,1.0,H,...,7.3,1.55,3.90,6.51,NaN,NaN,NaN,NaN,NaN,NaN
5138,Brazil,Serie A,2025,26/08/2025,01:00,Flamengo RJ,Vitoria,8.0,0.0,H,...,16.0,1.18,6.47,15.25,1.2,7.6,24.0,1.18,6.5,15.0

In [28]:
df.sort_values("PSCH", ascending=True)  #ordenando em ordem decrecente pelo ODD da Casa

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,...,MaxCA,AvgCH,AvgCD,AvgCA,BFECH,BFECD,BFECA,B365CH,B365CD,B365CA
2939,Brazil,Serie A,2019,27/10/2019,22:00,Flamengo RJ,CSA,1.0,0.0,H,...,36.00,1.07,10.82,26.58,NaN,NaN,NaN,NaN,NaN,NaN
3029,Brazil,Serie A,2019,05/12/2019,23:00,Flamengo RJ,Avai,6.0,1.0,H,...,29.00,1.10,9.53,21.17,NaN,NaN,NaN,NaN,NaN,NaN
2969,Brazil,Serie A,2019,08/11/2019,00:00,Gremio,CSA,2.0,1.0,H,...,22.00,1.15,7.37,17.73,NaN,NaN,NaN,NaN,NaN,NaN
2914,Brazil,Serie A,2019,17/10/2019,01:00,Palmeiras,Chapecoense-SC,1.0,0.0,H,...,22.00,1.16,6.89,17.20,NaN,NaN,NaN,NaN,NaN,NaN
4122,Brazil,Serie A,2022,23/10/2022,01:00,Palmeiras,Avai,3.0,0.0,H,...,21.00,1.16,7.47,17.28,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5560,Brazil,Serie A,2026,30/08/2026,20:00,Flamengo RJ,Botafogo RJ,3.0,0.0,H,...,11.00,1.28,5.55,9.37,1.32,6.20,11.5,1.25,5.75,10.00
5561,Brazil,Serie A,2026,30/08/2026,22:30,Gremio,Chapecoense-SC,3.0,1.0,H,...,6.50,1.52,4.01,6.05,1.57,4.30,7.4,1.49,4.00,6.50
5562,Brazil,Serie A,2026,30/08/2026,22:30,Mirassol,Palmeiras,1.0,1.0,D,...,2.15,3.42,3.30,2.10,3.80,3.45,2.2,3.70,3.50,2.01
5563,Brazil,Serie A,2026,30/08/2026,23:30,Bahia,Internacional,3.0,2.0,H,...,4.50,1.78,3.58,4.28,1.88,3.75,4.8,1.76,3.60,4.50
5564,Brazil,Serie A,2026,01/09/2026,00:00,Remo,Coritiba,2.0,3.0,A,...,3.80,2.04,3.20,3.70,2.16,3.35,4.0,2.05,3.30,3.75

# Dados Interpretados

## Informações Gerais da Partida

| Campo   | Descrição                                      |
|---------|------------------------------------------------|
| **Country** | País onde a liga/campeonato é disputado.      |
| **League**  | Nome da liga ou torneio (ex: Premier League, Brasileirão). |
| **Season**  | Ano ou temporada correspondente ao jogo.      |
| **Date**    | Data de realização da partida.                |
| **Time**    | Horário de início da partida.                 |
| **Home**    | Nome do time mandante (casa).                 |
| **Away**    | Nome do time visitante (fora).                |

---

## Placar e Resultado Final

| Campo | Descrição |
|-------|-----------|
| **HG** (Home Goals) | Número de gols marcados pelo time mandante. |
| **AG** (Away Goals) | Número de gols marcados pelo time visitante. |
| **Res** (Result)    | Resultado final do jogo:<br>• **H** = Vitória da casa (Home)<br>• **D** = Empate (Draw)<br>• **A** = Vitória do visitante (Away) |

---

## Odds de Apostas (Cotações de Fechamento)

> A sigla no final das odds indica o mercado:  
> **CH** = Casa (Closing Home) · **CD** = Empate (Closing Draw) · **CA** = Visitante (Closing Away)  
> O **C** indica que são **odds de fechamento** (as cotações finais antes de a partida começar).

### Pinnacle

| Campo  | Descrição |
|--------|-----------|
| **PSCH** | Odd de fechamento da Pinnacle para vitória do mandante |
| **PSCD** | Odd de fechamento da Pinnacle para empate |
| **PSCA** | Odd de fechamento da Pinnacle para vitória do visitante |

### Estatísticas Gerais do Mercado

| Campo | Descrição |
|-------|-----------|
| **MaxCH / MaxCD / MaxCA** | Maior odd disponível no mercado para Casa, Empate e Visitante, respectivamente |
| **AvgCH / AvgCD / AvgCA** | Média das odds de todas as casas de apostas comparadas |

### Betfair Exchange (BFE)

| Campo   | Descrição |
|---------|-----------|
| **BFECH** | Odd de fechamento na bolsa de apostas Betfair Exchange para vitória do mandante |
| **BFECD** | Odd de fechamento na Betfair Exchange para empate |
| **BFECA** | Odd de fechamento na Betfair Exchange para vitória do visitante |

### Bet365 (B365)

| Campo    | Descrição |
|----------|-----------|
| **B365CH** | Odd de fechamento na Bet365 para vitória do mandante |
| **B365CD** | Odd de fechamento na Bet365 para empate |
| **B365CA** | Odd de fechamento na Bet365 para vitória do visitante |

-NOTA: essa estatistica não tinha pois a BET não existia antes disso

# Verificando Integridade dos dados

In [ ]:
# Verificando se há valores nulos
df.isnull()

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,...,MaxCA,AvgCH,AvgCD,AvgCA,BFECH,BFECD,BFECA,B365CH,B365CD,B365CA
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5560,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5561,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5562,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5563,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5564,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [33]:
#contagem de nulos
df.isnull().sum()
# nota-se que possui jogos sem odd da Pinnacle, dá BetFair e da Bet365(sendo essa maior possuidora de nulos)

Country       0
League        0
Season        0
Date          0
Time          0
Home          0
Away          0
HG            1
AG            1
Res           1
PSCH        290
PSCD        290
PSCA        290
MaxCH         0
MaxCD         0
MaxCA         0
AvgCH         0
AvgCD         0
AvgCA         0
BFECH      4735
BFECD      4735
BFECA      4735
B365CH     5118
B365CD     5118
B365CA     5118
dtype: int64

In [36]:
# Os nulos de Odd são muito altos e podem ser retirados dependendo das regras de negocio
df[df['HG'].isnull()]

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,...,MaxCA,AvgCH,AvgCD,AvgCA,BFECH,BFECD,BFECA,B365CH,B365CD,B365CA
1891,Brazil,Serie A,2016,11/12/2016,19:00,Chapecoense-SC,Atletico-MG,NaN,NaN,NaN,...,2.68,2.85,3.3,2.67,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
# O Jogo que está como nulo foi o do acidentwe do avião da chapecoense :(
# Uma forma de preencher isso é colocando 3 X 3 para ambos pois foi W.O

filtro = (
    df['Season'] == 2016) & (df['Home'] == 'Chapecoense-SC') & (df['HG'].isna())

df.loc[filtro, ['AG', 'HG']] = 3.0
df.loc[filtro, 'Res'] = 'D'

df[(df['Season'] == 2016) & (df['Home'] == 'Chapecoense-SC') & (df['Away'] == 'Atletico-MG')]

,Country,League,Season,Date,Time,Home,Away,HG,AG,Res,...,MaxCA,AvgCH,AvgCD,AvgCA,BFECH,BFECD,BFECA,B365CH,B365CD,B365CA
1891,Brazil,Serie A,2016,11/12/2016,19:00,Chapecoense-SC,Atletico-MG,3.0,3.0,D,...,2.68,2.85,3.3,2.67,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# verificando duplicatas , nesse caso há zero duplicatas
df.duplicated().sum()

np.int64(0)

In [ ]:
# verificando os nulos na Pinnacle
# Filtra se houver nulo em QUALQUER uma das 3 colunas da Pinnacle
colunas_pinnacle = ["PSCH", "PSCD", "PSCA"]

df[df[colunas_pinnacle].isna().any(axis=1)]
# como houve uma fusão de empresas a pinnacle deixou de exitir e por isso não esta mais nesse .csv

     Country   League  Season        Date   Time            Home  \
1891  Brazil  Serie A    2016  11/12/2016  19:00  Chapecoense-SC
5236  Brazil  Serie A    2025  29/10/2025  22:00      Fluminense
5237  Brazil  Serie A    2025  01/11/2025  19:00        Cruzeiro
5238  Brazil  Serie A    2025  01/11/2025  19:00          Santos
5239  Brazil  Serie A    2025  01/11/2025  21:00        Mirassol
...      ...      ...     ...         ...    ...             ...
5560  Brazil  Serie A    2026  30/08/2026  20:00     Flamengo RJ
5561  Brazil  Serie A    2026  30/08/2026  22:30          Gremio
5562  Brazil  Serie A    2026  30/08/2026  22:30        Mirassol
5563  Brazil  Serie A    2026  30/08/2026  23:30           Bahia
5564  Brazil  Serie A    2026  01/09/2026  00:00            Remo

                Away   HG   AG Res  ...  MaxCA  AvgCH  AvgCD  AvgCA  BFECH  \
1891     Atletico-MG  3.0  3.0   D  ...   2.68   2.85   3.30   2.67    NaN
5236           Ceara  1.0  0.0   H  ...   6.75   1.55   3.78   6.33   1.60
5237         Vitoria  3.0  1.0   H  ...   8.50   1.40   4.41   7.94   1.45
5238       Fortaleza  1.0  1.0   D  ...   5.25   1.67   3.76   4.94   1.74
5239     Botafogo RJ  0.0  0.0   D  ...   3.15   2.31   3.30   3.02   2.46
...              ...  ...  ...  ..  ...    ...    ...    ...    ...    ...
5560     Botafogo RJ  3.0  0.0   H  ...  11.00   1.28   5.55   9.37   1.32
5561  Chapecoense-SC  3.0  1.0   H  ...   6.50   1.52   4.01   6.05   1.57
5562       Palmeiras  1.0  1.0   D  ...   2.15   3.42   3.30   2.10   3.80
5563   Internacional  3.0  2.0   H  ...   4.50   1.78   3.58   4.28   1.88
5564        Coritiba  2.0  3.0   A  ...   3.80   2.04   3.20   3.70   2.16

      BFECD  BFECA  B365CH  B365CD  B365CA
1891    NaN    NaN     NaN     NaN     NaN
5236   4.00   7.60    1.60    3.80    6.00
5237   4.70   9.60    1.38    4.75    8.50
5238   4.00   5.70    1.67    3.70    5.25
5239   3.45   3.25    2.35    3.30    3.10
...     ...    ...     ...     ...     ...
5560   6.20  11.50    1.25    5.75   10.00
5561   4.30   7.40    1.49    4.00    6.50
5562   3.45   2.20    3.70    3.50    2.01
5563   3.75   4.80    1.76    3.60    4.50
5564   3.35   4.00    2.05    3.30    3.75

[290 rows x 25 columns]

In [ ]:
# Visão geral de Nulos (contagem absoluta e percentual)
nulos = df.isna().sum()
pct_nulos = (df.isna().sum() / len(df)) * 100
pd.DataFrame({'Nulos': nulos, '% Nulos': pct_nulos.round(2)})

         Nulos  % Nulos
Country      0     0.00
League       0     0.00
Season       0     0.00
Date         0     0.00
Time         0     0.00
Home         0     0.00
Away         0     0.00
HG           0     0.00
AG           0     0.00
Res          0     0.00
PSCH       290     5.21
PSCD       290     5.21
PSCA       290     5.21
MaxCH        0     0.00
MaxCD        0     0.00
MaxCA        0     0.00
AvgCH        0     0.00
AvgCD        0     0.00
AvgCA        0     0.00
BFECH     4735    85.09
BFECD     4735    85.09
BFECA     4735    85.09
B365CH    5118    91.97
B365CD    5118    91.97
B365CA    5118    91.97

In [55]:
# 5. Resumo estatístico das Odds/Gols (para detectar valores absurdos ou negativos)
df.describe().T[['min', 'max','mean']]

            min      max         mean
Season  2012.00  2026.00  2018.830189
HG         0.00     8.00     1.425157
AG         0.00     6.00     0.973585
PSCH       1.08    17.68     2.309354
PSCD       2.54    12.25     3.635761
PSCA       1.15    29.58     4.677033
MaxCH      1.09    29.00     2.384960
MaxCD      2.63    12.50     3.735608
MaxCA      0.00    36.00     4.893098
AvgCH      1.07    20.23     2.236171
AvgCD      2.51    10.82     3.487184
AvgCA      1.15    26.58     4.325668
BFECH      1.16    11.50     2.410024
BFECD      2.82     9.60     3.689229
BFECA      1.38    24.00     4.922434
B365CH     1.13     9.00     2.265123
B365CD     2.75     7.50     3.567383
B365CA     1.35    17.00     4.372192

In [ ]:

# Checar se a regra de resultado (Res) bate com os gols (HG x AG)
# Exemplo: Jogos com resultado 'H' onde o time da casa não fez mais gols
inconsistencias = df[
    ((df['Res'] == 'H') & (df['HG'] <= df['AG'])) |
    ((df['Res'] == 'A') & (df['AG'] <= df['HG'])) |
    ((df['Res'] == 'D') & (df['HG'] != df['AG']))
]
len(inconsistencias)

0

# Finalizando tratamento e exploração de Dados

In [59]:
df

     Country   League  Season        Date   Time          Home  \
0     Brazil  Serie A    2012  19/05/2012  22:30     Palmeiras
1     Brazil  Serie A    2012  19/05/2012  22:30  Sport Recife
2     Brazil  Serie A    2012  20/05/2012  01:00   Figueirense
3     Brazil  Serie A    2012  20/05/2012  20:00   Botafogo RJ
4     Brazil  Serie A    2012  20/05/2012  20:00   Corinthians
...      ...      ...     ...         ...    ...           ...
5560  Brazil  Serie A    2026  30/08/2026  20:00   Flamengo RJ
5561  Brazil  Serie A    2026  30/08/2026  22:30        Gremio
5562  Brazil  Serie A    2026  30/08/2026  22:30      Mirassol
5563  Brazil  Serie A    2026  30/08/2026  23:30         Bahia
5564  Brazil  Serie A    2026  01/09/2026  00:00          Remo

                Away   HG   AG Res  ...  MaxCA  AvgCH  AvgCD  AvgCA  BFECH  \
0         Portuguesa  1.0  1.0   D  ...   5.31   1.69   3.50   4.90    NaN
1        Flamengo RJ  1.0  1.0   D  ...   2.70   2.59   3.23   2.58    NaN
2            Nautico  2.0  1.0   H  ...   7.22   1.59   3.67   5.64    NaN
3          Sao Paulo  4.0  2.0   H  ...   3.15   2.35   3.26   2.84    NaN
4         Fluminense  0.0  1.0   A  ...   4.41   1.89   3.33   3.89    NaN
...              ...  ...  ...  ..  ...    ...    ...    ...    ...    ...
5560     Botafogo RJ  3.0  0.0   H  ...  11.00   1.28   5.55   9.37   1.32
5561  Chapecoense-SC  3.0  1.0   H  ...   6.50   1.52   4.01   6.05   1.57
5562       Palmeiras  1.0  1.0   D  ...   2.15   3.42   3.30   2.10   3.80
5563   Internacional  3.0  2.0   H  ...   4.50   1.78   3.58   4.28   1.88
5564        Coritiba  2.0  3.0   A  ...   3.80   2.04   3.20   3.70   2.16

      BFECD  BFECA  B365CH  B365CD  B365CA
0       NaN    NaN     NaN     NaN     NaN
1       NaN    NaN     NaN     NaN     NaN
2       NaN    NaN     NaN     NaN     NaN
3       NaN    NaN     NaN     NaN     NaN
4       NaN    NaN     NaN     NaN     NaN
...     ...    ...     ...     ...     ...
5560   6.20   11.5    1.25    5.75   10.00
5561   4.30    7.4    1.49    4.00    6.50
5562   3.45    2.2    3.70    3.50    2.01
5563   3.75    4.8    1.76    3.60    4.50
5564   3.35    4.0    2.05    3.30    3.75

[5565 rows x 25 columns]

In [62]:
df.to_csv("/home/luis/Projetos/scooutMax/data/silver/BRA_limpo.csv", index=False)